title: "Julie Boisard, PhD"
description: "Researcher in Courtney Stairs' lab at Lund University"
author: "Julie Boisard"
url: "https://julieboisard.github.io"

plugins:
  - jekyll-seo-tag # Optional, improves search engine optimization
  - jekyll-feed    # Optional, adds RSS feed
  - jekyll-remote-theme
  - jekyll-github-metadata

remote_theme: pages-themes/minimal@v0.2.0

markdown: kramdown
highlighter: rouge

logo: "/assets/images/photo_1.png"
logo_width: 100px

univprofile: "https://portal.research.lu.se/en/persons/julie-boisard"
googlescholar: "https://scholar.google.com/citations?hl=en&user=ta45Ne0AAAAJ"
orcid: "https://orcid.org/0000-0002-6191-6149"
bluesky: "https://bsky.app/profile/protistsforthewin.bsky.social"
github.is_user_page: "https://github.com/julieboisard"

# cv: "/assets/cv/cv.pdf"